name: Deploy to GitHub Pages

on:
  push: 
    branches: [ release ] # is triggered if push event in release branch occurs
jobs:
  build:
    runs-on: ubuntu-latest # run ubuntu
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout your repo - this is an official action provided by GitHub

      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Build project files
        run: npm run docs:build # creates a /dist directory with build files

      - name: Setup GH Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .vitepress/dist # path to build files directory

      - name: Deploy to GH Pages # deploy
        id: deployment
        uses: actions/deploy-pages@v1
